on:
  push:
    branches:    
      - master
      
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
 
name: build-and-deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    - name: Build webapp
      run: |
        make webapp/setup
        make webapp/build
     
    - name: Build hugo
      run: |
        make hugo/build
      
      
      # sftp action fails with dirty files in repo
      # we must reset these files
      # modified:   app/frontend/package-lock.json
      # modified:   hugo/layouts/index.gen.html
      # this works because ./public is not in git index
    - name: Prepare SFTP
      run: |
        git reset --hard
    - name: List output files
      run: |
        ls -al
        ls -al ./public
        ls -al ./public/blog/
        git status
    
    
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.7
      if: github.ref == 'refs/heads/master'
      with:
        sftp: true # optional
        host: ${{ secrets.server }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
        port: 5544 # optional, default is: 21
        username: ${{ secrets.username }}  # FTP username
        password: ${{ secrets.password }} # FTP password
        # remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }} # optional, remote path of your FTP server
        local_folder: public
        cleanup: false # optional, remove existing files inside FTP remote folder
        include: '["*"]' # optional, e.g. '['dist']'
        exclude: '[]' # optional, e.g. '['node_modules/**', '.git/**', '*.env']'
        passive: true # optional
